apiVersion: v2
name: keycloak-operator
description: Keycloak operator for Kubernetes
type: application
version: 0.1.3
appVersion: "26.5.3"
home: https://www.keycloak.org/operator/installation
sources:
  - https://github.com/keycloak/keycloak-k8s-resources
  - https://github.com/px3-dev/keycloak-operator
maintainers:
  - name: px3-dev
