
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-clusterrole-binding
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "keycloak-operator.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
