
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-role-binding
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "keycloak-operator.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-operator.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-realmimport-role-binding
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "keycloak-operator.fullname" . }}-realmimport-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-operator.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-keycloak-role-binding
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "keycloak-operator.fullname" . }}-keycloak-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-operator.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-view
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-operator.serviceAccountName" . }}
